spring:
  application:
  name: geocalculator_service
server:
  port: 8181
  error:
    include-message: ALWAYS
  datasource:
    url: jdbc:h2:mem:test
    username: guest
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop